### ISSUE TITLE
Run Cosmas inside Docker container

### ISSUE THREAD

**Issue by dbarashev** [bardsoftware/papeeria-edit-history#10]
We can run Cosmas with `gradle run`, now let's take a step further and package it into docker container.

We need a Dockerfile which would package Cosmas distribution (server component in particular) into docker image based e.g. on [openjdk:8-slim](https://hub.docker.com/_/openjdk/). Please notice that we don't want to run `gradle` in the container, we want to run already compiled application. `gradle distZip` will build a ZIP file with a ready to run app and will put it into `build/distributions` directory.

**Comment by SashaOrlova** [comment]
did I understand right, that Dokerfile need unzip file and run it?

**Comment by dbarashev** [comment]
Well, you don't want to run the application in dockerfile, if you meant exactly [RUN instruction](https://docs.docker.com/engine/reference/builder/#run), because it runs when you build the image, not when you run the container. But yes, if you unzip and make an entrypoint from the launcher script, it should do the trick.
