### ISSUE TITLE
Create a demo page with ACE editor

### ISSUE THREAD

**Issue by dbarashev** [bardsoftware/papeeria-edit-history#4]
Production Papeeria service uses ACE editor. We're not yet changing production code, but we need demo UI which we could use for development of UI-related features.

As the very first step, let's create a simple HTML page with embedded ACE editor. Refer to [ACE docs](https://ace.c9.io/) for examples of such page.

Please put all HTML, JS and CSS files into `demo` folder.

**Comment by SashaOrlova** [comment]
Ok, start working on Friday
