### ISSUE TITLE
Create basic GRPC server

### ISSUE THREAD

**Issue by dbarashev** [bardsoftware/papeeria-edit-history#5]
So we now have nice service definition in `cosmas.proto`. Let's create a basic runnable GRPC server which implements our `Cosmas` service. Refer to the [docs on grpc-java](https://grpc.io/docs/tutorials/basic/java.html).  For now we only need what is called a simple RPC in the docs.

Please write the server code in Kotlin. Although there is no special grpc-kotlin, Java and Kotlin are very interoperable languages.

**Comment by iisuslik43** [comment]
Almost done, i will open pull request on Friday or Saturday

**Comment by dbarashev** [comment]
Cool, thanks. In fact, I recommend doing git commit and git push frequently. It is not necessary to wait until everything is ready and do commit+push+pull request at once. Commit and push your work once you reach some meaningful milestone (e.g. added a stub implementation of some interface). This will show us that there is some progress in your work and will save your work from disasters.
