### ISSUE TITLE
Primitive in-memory implementation of file version storage

### ISSUE THREAD

**Issue by dbarashev** [bardsoftware/papeeria-edit-history#8]
Let's expand our Cosmas service and create a primitive in-memory implementation with the following methods:
```
createVersion
getVersion
```

Method `createVersion` saves file text as a new record in the history. Every file has a string identifier (which is a long hexadecimal sequence) and identifier of the project where the file belongs to (project identifier is also a long hexadecimal sequence written as a string). Project id is not needed for file identification, but it may be used later for the history parameters (e.g. we may restrict some projects to short file histories and allow longer file histories for other projects).

Besides the identifiers, every `createVersion` request naturally requires file contents which is a byte array in common case (because there may be binary files).

Method `getVersion` will in the future accept version identifier in the request, but for this primitive implementation we'll be very dumb: just ignore the request and return the latest version. The response shall return byte array.

So we need these methods and request/response objects in the protocol buffers, their in-memory implementation and tests, of course.

**Comment by iisuslik43** [comment]
OK, I will start doing it today.
